const {callCloud}=require("../../services/cloud");
const {ensureAppLogin}=require("../../utils/session");
const {decorate}=require("../../utils/plan");
const cache=require("../../utils/cache");
Page({
 data:{planId:"",loading:true,error:"",detail:null,plan:null,busy:false,buttonLabel:"报名一起爬",buttonDisabled:false,stateText:""},
 onLoad(q){this.setData({planId:String(q.planId||"")});},onShow(){this.load();},
 async onPullDownRefresh(){try{await this.load();}finally{wx.stopPullDownRefresh();}},
 onShareAppMessage(){const p=this.data.plan||{};return {title:p.title||"一起爬，认识新岩友",path:"/pages/plan-detail/index?planId="+encodeURIComponent(this.data.planId)};},
 async load(){this.setData({loading:true,error:""});try{const d=await callCloud("calendar_plan_publish",{action:"detail",planId:this.data.planId},{silent:true});const p=decorate(d.plan);let text="",label="报名一起爬",disabled=false;const ended=p.endAt<=Date.now();if(p.status==='cancelled'){text="这场约爬已取消";label="已取消";disabled=true;}else if(ended){text="这场约爬已结束，期待下次一起爬";label="已结束";disabled=true;}else if(d.myStatus==='confirmed'){text="你已确认参加，记得查看集合信息";label="取消报名";}else if(d.myStatus==='pending'){text="申请已提交，等待发起人确认。确认前还未约成。";label="取消申请";}else if(d.myStatus==='removed'){text="发起人已移除你的报名";label="无法再次报名";disabled=true;}else if(d.isBlocked){text="当前无法报名该约爬";disabled=true;label="无法报名";}else if((p.joinDeadline||p.endAt)<=Date.now()){text="报名已截止";label="报名已截止";disabled=true;}else if(p.full&&p.joinMode!=='approval'){label="名额已满";disabled=true;}else if(p.joinMode==='approval'){label="申请加入";text="发起人确认后才算约成";}this.setData({detail:d,plan:p,stateText:text,buttonLabel:label,buttonDisabled:disabled,ended});}catch(e){this.setData({error:e.code==='FORBIDDEN'?"这场约爬仅向指定岩友开放":e.code==='NOT_FOUND'?"这场约爬不存在或已删除":"约爬暂时加载失败，请重试"});}finally{this.setData({loading:false});}},
 async act(action,targetOpenid){if(this.data.busy)return;this.setData({busy:true});try{await ensureAppLogin();await callCloud("calendar_plan_publish",{action,planId:this.data.planId,targetOpenid},{silent:true});cache.invalidate(cache.CACHE_KEYS.CALENDAR_SUMMARY);try{getApp().globalData.plansDirty=true;}catch(_){}await this.load();wx.showToast({title:"已更新",icon:"success"});}catch(e){if(e.code==='PROFILE_REQUIRED'){wx.showModal({title:"让新岩友认识你",content:"先填写昵称，再回来报名。",confirmText:"填写资料",success:r=>{if(r.confirm)wx.navigateTo({url:"/pages/profile-edit/index"});}});}else wx.showModal({title:"暂未完成",content:e.message||"请稍后重试",showCancel:false});}finally{this.setData({busy:false});}},
 mainAction(){if(this.data.buttonDisabled)return;const status=this.data.detail.myStatus;if(status==='confirmed'||status==='pending'){wx.showModal({title:"取消本次报名？",content:"发起人会在站内收到通知。",success:r=>{if(r.confirm)this.act('unjoin_plan');}});}else this.act('join_plan');},
 approve(e){this.act('approve_joiner',e.currentTarget.dataset.id);},reject(e){this.act('reject_joiner',e.currentTarget.dataset.id);},
 remove(e){const id=e.currentTarget.dataset.id;wx.showModal({title:"移除这位岩友？",content:"对方会收到站内通知，名额将释放。",success:r=>{if(r.confirm)this.act('remove_joiner',id);}});},
 cancel(){wx.showModal({title:"取消这场约爬？",content:"已报名的岩友会收到站内通知。",confirmText:"取消约爬",success:r=>{if(r.confirm)this.act('cancel');}});},
 edit(){wx.navigateTo({url:"/pages/calendar-publish/index?planId="+encodeURIComponent(this.data.planId)});},
 again(){const p=this.data.plan;const q=["gymId="+encodeURIComponent(p.gymId||""),"city="+encodeURIComponent((p.gymSnapshot||{}).city||""),"skillTags="+encodeURIComponent((p.skillTags||[]).join(",")),"atmosphere="+encodeURIComponent((p.atmosphereTags||[]).join(",")),"capacity="+encodeURIComponent(p.capacity?String(p.capacity):""),"joinMode="+encodeURIComponent(p.joinMode==="approval"?"approval":"direct"),"again=1"].join("&");wx.navigateTo({url:"/pages/calendar-publish/index?"+q});},
 addFriend(e){const target=e.currentTarget.dataset.id;wx.showModal({title:"添加为岩友",content:"向这位岩友发送好友申请？",success:async r=>{if(!r.confirm)return;try{await ensureAppLogin();await require("../../services/api/friendship").request({toOpenid:target});wx.showToast({title:"已发送申请",icon:"success"});}catch(e){wx.showToast({title:e.message||"申请失败",icon:"none"});}}});},
 copyContact(){wx.setClipboardData({data:this.data.detail.contact});},
 more(){wx.showActionSheet({itemList:["举报这场约爬","屏蔽发起人"],success:r=>{if(r.tapIndex===0)this.report();else this.block();}});},
 report(){wx.showModal({title:"举报约爬",editable:true,placeholderText:"请说明原因，便于管理员处理",success:async r=>{if(!r.confirm||!r.content.trim())return;try{await ensureAppLogin();await callCloud("calendar_plan_publish",{action:"report",planId:this.data.planId,reason:r.content},{silent:true});wx.showToast({title:"已提交举报",icon:"success"});}catch(e){wx.showToast({title:e.message||"提交失败",icon:"none"});}}});},
 block(){wx.showModal({title:"屏蔽这位发起人？",content:"双方将无法新增报名或好友申请。已报名的约爬可先取消；你也可以在我的页面解除屏蔽。",success:async r=>{if(!r.confirm)return;try{await callCloud("calendar_plan_publish",{action:"block",targetOpenid:this.data.detail.ownerInfo.openid},{silent:true});await this.load();}catch(e){wx.showToast({title:e.message||"操作失败",icon:"none"});}}});}
});
